### ISSUE TITLE
License Concerns

### ISSUE THREAD

**Issue by bobpaul** [pietrop/ffmpeg-static-electron#2]
So this repo seems to be licensed under a custom BSD like license.

But you're clearly dependent on FFmpeg, which is GPLv2/GPLv3 and (or if properly compiled and documented, LGPLv2/LGPLv3). 

I see you're re-distributing binaries for FFmpeg. Not only that, you're re-distributing binaries built by Zeranoe. All of the Zeranoe builds are expressly (L)GPLv3 (with nightly builds available only under GPLv3):
![image](https://user-images.githubusercontent.com/90864/82754738-9cd2c200-9d94-11ea-9629-e17713fe73f9.png)

FFmpeg has some [notes on license compliance](https://www.ffmpeg.org/legal.html), and I'm not convinced your project is compliant. Worse, by licensing your project under a BSD-like license without any mention that the FFmpeg binaries you're distributing are GPLv3, I think you mislead others who might use this project to include FFmpeg in projects that aren't compatible with GPLv3.

I would recommend you reach out to the FFmpeg project to see what changes they might recommend. The easiest paths are probably to re-license this project under GPLv3 or stop distributing FFmpeg binaries and instead automate the fetching of those binaries. Either way, I do think you need to be explicit about what license FFmpeg is using.

**Comment by pietrop** [comment]
Thanks @bobpaul 
The licence you see in this repo is from the origin repo, you might want to raise an issue there as well. 

For now changing this one to [GPLv3](https://choosealicense.com/licenses/agpl-3.0/) as a quick fix. 

Let me know if you have any other concerns
